#!/bin/bash

#use arg or stdin
arg="${1:-$(IFS= read -r line && echo "$line")}"


if [ -n "$arg" ]; then
sed -i "/bgcolor/c\bgcolor=$arg" /home/gechternacht/.config/nitrogen/bg-saved.cfg ; nitrogen --restore &
fi
