#!/bin/bash
(cd ~/.config/polybar; 
	selected_branch=$(git branch -l | sed 's/\*/ /' | sed 's/ //g'  | dmenu -c -i -l 10 -nb "#4e4b61" -sf "#4e4b61" -sb "#c1b492" -nf "#c1b492" -p "❒ theme:");
	git checkout "$selected_branch";
	polybar-restart
	)